import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

const TRANSLATIONS = {
  en: {
    // Nav Items
    "nav.dashboard": "Dashboard",
    "nav.pos": "Quick POS",
    "nav.invoices": "Invoices",
    "nav.purchases": "Purchases",
    "nav.waybills": "E-Waybills",
    "nav.inventory": "Inventory",
    "nav.customers": "Customers",
    "nav.expenses": "Expenses",
    "nav.accounting": "Accounting",
    "nav.loans": "Loans",
    "nav.barcode": "Barcode",
    "nav.gstfiling": "GST Filing",
    "nav.reports": "Reports",
    "nav.aiinsights": "AI Insights",
    "nav.settings": "Settings",
    "nav.upgrade": "Upgrade",
    "nav.logout": "Logout",
    "nav.branches": "Branches",
    "nav.invsync": "Inventory Sync",
    "nav.stocktransfer": "Stock Transfer",
    "nav.warehouse": "Warehouse Hub",
    "nav.enterprise_intel": "Enterprise Intel",
    "nav.finance": "Finance Hub",
    "nav.auditLogs": "Audit Logs",
    "nav.manufacturing": "Manufacturing ERP",
    "nav.hrms": "HRMS & Payroll",
    "nav.supermarket_counters": "Counter Mgmt",
    "nav.supermarket_offers": "Offers Engine",
    "nav.supermarket_loyalty": "Loyalty Program",
    "nav.supermarket_expiry": "Expiry Mgmt",
    "nav.supermarket_reports": "Dept Reports",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.update": "Update",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.print": "Print",
    "common.download": "Download",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.loading": "Loading...",
    "common.saving": "Saving...",
    "common.no_data": "No data found",
    "common.view_all": "View All",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.total": "Total",
    "common.name": "Name",
    "common.phone": "Phone",
    "common.email": "Email",
    "common.address": "Address",
    "common.category": "Category",
    "common.type": "Type",
    "common.active": "Active",
    "common.all": "All",
    "common.paid": "Paid",
    "common.unpaid": "Unpaid",
    "common.partial": "Partial",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.details": "Details",
    "common.from": "From",
    "common.to": "To",
    "common.today": "Today",
    "common.this_month": "This Month",
    "common.this_year": "This Year",

    // Greetings
    "greeting.namaste": "Namaste",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Business overview at a glance",
    "dashboard.welcome": "Welcome back",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.create_invoice": "Create Invoice",
    "dashboard.add_product": "Add Product",
    "dashboard.add_customer": "Add Customer",
    "dashboard.new_purchase": "New Purchase",
    "dashboard.view_reports": "View Reports",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.business_summary": "Business Summary",

    // Settings
    "settings.title": "️ Settings",
    "settings.subtitle": "Configure your business profile",
    "settings.shop_name": "Shop / Business Name",
    "settings.business_type": "Business Type",
    "settings.gst_number": "GST Number",
    "settings.pan_number": "PAN Number",
    "settings.phone": "Phone Number",
    "settings.email": "Email Address",
    "settings.address": "Business Address",
    "settings.city": "City",
    "settings.state": "State",
    "settings.pincode": "Pincode",
    "settings.logo": "Business Logo",
    "settings.signature": "Digital Signature",
    "settings.save_settings": "Save Settings",
    "settings.general": "General",
    "settings.branding": "Branding",
    "settings.billing": "Billing",
    "settings.printer_settings": "Printer Settings",
    "settings.bank_details": "Bank Account Details",
    "settings.account_number": "Account Number",
    "settings.bank_name": "Bank Name",
    "settings.ifsc_code": "IFSC Code",
    "settings.branch": "Branch",
    "settings.upi_id": "UPI ID",
    "settings.invoice_prefix": "Invoice Prefix",
    "settings.terms_conditions": "Terms & Conditions",
    "settings.terms_placeholder": "Terms text...",
    "settings.invoice_title": "Invoice Configuration",
    "settings.branding_desc": "Upload your shop logo and digital signature to appear on printed invoices.",
    "settings.change_logo": "Change Logo",
    "settings.upload_logo": "Upload Logo",
    "settings.logo_requirements": "PNG, JPG up to 2MB. Recommended: 300×100px",
    "settings.change_signature": "Change Signature",
    "settings.upload_signature": "Upload Signature",
    "settings.sig_requirements": "PNG with transparent background recommended",
    "settings.appearance": "Appearance",
    "settings.appearance_desc": "Customize the look and feel of the POS terminal and dashboard.",
    "settings.theme_preference": "Theme Preference",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.business_entity_type": "Business Entity Type",
    "settings.select_entity_type": "Select Entity Type",
    "settings.search_entity_type": "Search entity type...",
    "settings.owner_name": "Owner / Proprietor Name",
    "settings.select_state": "Select State",
    "settings.search_state": "Search state...",
    "settings.select_layout": "Select Layout",
    "settings.search_layout": "Search layout...",
    "settings.enter_custom_business": "Enter your business type...",
    "settings.business_type_desc": "Sets the default industry-specific theme & fields inside your POS billing terminal.",

    // Inventory
    "inventory.title": "Inventory",
    "inventory.subtitle": "Manage your products and stock",
    "inventory.add_product": "Add Product",
    "inventory.edit_product": "Edit Product",
    "inventory.product_name": "Product Name",
    "inventory.selling_price": "Selling Price",
    "inventory.purchase_price": "Purchase Price",
    "inventory.stock": "Stock",
    "inventory.current_stock": "Current Stock",
    "inventory.min_stock": "Min Stock Level",
    "inventory.gst_rate": "GST Rate",
    "inventory.hsn_code": "HSN Code",
    "inventory.barcode": "Barcode",
    "inventory.category": "Category",
    "inventory.unit": "Unit",
    "inventory.stock_value": "Stock Value",
    "inventory.in_stock": "In Stock",
    "inventory.low_stock": "Low Stock",
    "inventory.out_of_stock": "Out of Stock",
    "inventory.total_products": "Total Products",
    "inventory.total_value": "Total Value",
    "inventory.stock_adjust": "Stock Adjustment",
    "inventory.stock_in": "Stock In",
    "inventory.stock_out": "Stock Out",
    "inventory.set_exact": "Set Exact",
    "inventory.quantity": "Quantity",
    "inventory.reason": "Reason",
    "inventory.purchase_grn": "Purchase / GRN",
    "inventory.customer_return": "Return from Customer",
    "inventory.transfer_in": "Stock Transfer In",
    "inventory.opening_stock": "Opening Stock",
    "inventory.sale_billing": "Sale / Billing",
    "inventory.damage_wastage": "Damage / Wastage",
    "inventory.transfer_out": "Stock Transfer Out",
    "inventory.expired": "Expired",
    "inventory.physical_count": "Physical Count",
    "inventory.audit_correction": "Audit Correction",
    "inventory.other": "Other",
    "inventory.after": "After",
    "inventory.change": "Change",
    "inventory.bulk_select": "Bulk",
    "inventory.delete_selected": "Delete Selected",
    "inventory.no_products": "No Products Found",
    "inventory.add_first": "Add your first product to get started",
    "inventory.sort_by": "Sort By",
    "inventory.all_categories": "All Categories",
    "inventory.all_stock": "All Stock",
    "inventory.stock_status": "Stock Status",
    "inventory.showing": "Showing",
    "inventory.of": "of",
    "inventory.products": "products",
    "inventory.branch_view": "Branch stock view",
    "inventory.global_catalog": "Global catalog",

    // Invoices
    "invoices.title": "Invoices",
    "invoices.subtitle": "Manage your sales invoices",
    "invoices.create": "Create Invoice",
    "invoices.invoice_number": "Invoice Number",
    "invoices.customer_name": "Customer Name",
    "invoices.invoice_date": "Invoice Date",
    "invoices.due_date": "Due Date",
    "invoices.grand_total": "Grand Total",
    "invoices.paid": "Paid",
    "invoices.unpaid": "Unpaid",
    "invoices.overdue": "Overdue",
    "invoices.no_invoices": "No invoices yet",
    "invoices.total_invoices": "total invoices",
    "invoices.sale_invoice": "Sale Invoice",
    "invoices.credit_note": "Credit Note",
    "invoices.debit_note": "Debit Note",
    "invoices.credit_notes": "Credit Notes",
    "invoices.debit_notes": "Debit Notes",
    "invoices.all": "All",
    "invoices.search_placeholder": "Search invoice or customer...",
    "invoices.toast_saved": "Invoice saved!",
    "invoices.toast_updated": "Invoice updated!",
    "invoices.toast_created": "Invoice created!",
    "invoices.toast_pdf_generating": "Generating & uploading PDF bill...",
    "invoices.toast_whatsapp_opened": "WhatsApp opened!",
    "invoices.toast_pdf_failed": "Failed to share PDF: ",
    "invoices.interstate": "Interstate",
    "invoices.due": "Due",
    "invoices.days_overdue": "days overdue",

    // Customers
    "customers.title": "Customers",
    "customers.subtitle": "Manage your customer database",
    "customers.add": "Add Customer",
    "customers.name": "Customer Name",
    "customers.phone": "Phone Number",
    "customers.outstanding": "Outstanding Balance",
    "customers.no_customers": "No customers found",
    "customers.contact_person": "Contact Person Name",
    "customers.gstin": "GSTIN",
    "customers.address": "Address",
    "customers.city": "City",
    "customers.state": "State",
    "customers.pincode": "Pincode",
    "customers.credit_limit": "Credit Limit",
    "customers.category": "Category",
    "customers.notes": "Notes",
    "customers.edit": "Edit Customer",
    "customers.delete_confirm": "Delete this customer?",
    "customers.search_placeholder": "Search customers...",
    "customers.business_name": "Customer / Business Name",
    "customers.toast_added": "Customer added!",
    "customers.toast_updated": "Customer updated!",
    "customers.toast_deleted": "Customer deleted",

    // Purchases
    "purchases.title": "Purchases",
    "purchases.subtitle": "Manage vendor purchases & GRN",
    "purchases.add": "New Purchase",
    "purchases.vendor_name": "Vendor Name",
    "purchases.total_amount": "Total Amount",
    "purchases.no_purchases": "No purchases yet",
    "purchases.purchase_entries_count": "purchase entries recorded",
    "purchases.portal_header": "Purchase Entry Portal",
    "purchases.gst_compliant": "GST COMPLIANT",
    "purchases.edit_entry": "Edit Purchase Entry",
    "purchases.new_entry": "New Purchase Entry",
    "purchases.vendor_details": "Vendor & Invoice Details",
    "purchases.vendor_name_label": "Vendor Name *",
    "purchases.vendor_phone_label": "Vendor Phone",
    "purchases.vendor_gstin_label": "Vendor GSTIN",
    "purchases.date_label": "Purchase Date",
    "purchases.invoice_no_label": "Vendor Invoice No.",
    "purchases.items_cart": "Purchase Items & Cart",
    "purchases.search_placeholder": "Scan barcode or type name to search...",
    "purchases.quick_add_product": "Quick Add Product",
    "purchases.prev_purchased": "Previously Purchased from this Vendor:",
    "purchases.product_details": "Product Details",
    "purchases.qty": "Qty",
    "purchases.buy_price": "Buy Price",
    "purchases.gst_pct": "GST %",
    "purchases.no_items": "No items added yet. Search products or add a new product above.",
    "purchases.payment_terms": "Payment Terms",
    "purchases.payment_status": "Payment Status",
    "purchases.amount_paid": "Amount Paid",
    "purchases.due_amount": "Due Amount",
    "purchases.payment_mode": "Payment Mode",
    "purchases.due_date": "Due Date (When to pay) *",
    "purchases.remarks": "Remarks / Notes",
    "purchases.grand_total": "Grand Total",
    "purchases.save_order": "Save Purchase Order",
    "purchases.paid": "Paid",
    "purchases.partial": "Partial",
    "purchases.unpaid": "Unpaid / Due",
    "purchases.cash": "Cash",
    "purchases.upi": "UPI / Scanner",
    "purchases.bank": "Bank Transfer",
    "purchases.credit": "Supplier Credit",
    "purchases.due_label": "Due:",
    "purchases.pay_by_label": "Pay by:",
    "purchases.toast_created": "Purchase entry created & stock synced!",
    "purchases.toast_updated": "Purchase entry updated!",

    // Expenses
    "expenses.title": "Expenses",
    "expenses.subtitle": "Track your business expenses",
    "expenses.add": "Add Expense",
    "expenses.amount": "Amount",
    "expenses.category": "Category",
    "expenses.no_expenses": "No expenses recorded",
    "expenses.total_this_month": "Total This Month",
    "expenses.title_tracker": "Expense Tracker",
    "expenses.subtitle_tracker": "Track all business expenses & operational costs",
    "expenses.total": "Total Expenses",
    "expenses.entries": "Total Entries",
    "expenses.categories": "Categories",
    "expenses.breakdown": "Category Breakdown",
    "expenses.search_placeholder": "Search expenses...",
    "expenses.all_categories": "All Categories",
    "expenses.edit": "Edit Expense",
    "expenses.gst_amount": "GST Amount",
    "expenses.paid_to": "Paid To",
    "expenses.payment_mode": "Payment Mode",
    "expenses.ref_no": "Reference No.",

    // Loans
    "loans.title": "Loans",
    "loans.subtitle": "Manage business loans & EMI",
    "loans.add": "Add Loan",
    "loans.lender_name": "Lender Name",
    "loans.principal": "Principal Amount",
    "loans.outstanding": "Outstanding Balance",
    "loans.interest_rate": "Interest Rate",
    "loans.active": "Active",
    "loans.closed": "Closed",
    "loans.no_loans": "No loans found",

    // Accounting
    "accounting.title": "Accounting",
    "accounting.subtitle": "Profit & loss, balance sheet",
    "accounting.profit_loss": "Profit & Loss",
    "accounting.balance_sheet": "Balance Sheet",
    "accounting.revenue": "Revenue",
    "accounting.gross_profit": "Gross Profit",
    "accounting.net_profit": "Net Profit",
    "accounting.title_page": "Accounting & P&L",
    "accounting.subtitle_page": "Full financial overview & profit/loss analysis",
    "accounting.total_revenue": "Total Revenue",
    "accounting.total_purchases": "Total Purchases",
    "accounting.total_expenses": "Total Expenses",
    "accounting.gst_collected": "GST Collected",
    "accounting.profit_margin": "Profit Margin",
    "accounting.loan_liability": "Loan Liability",
    "accounting.monthly_chart_title": "Monthly Revenue & Profit",
    "accounting.profit_trend": "Profit Trend",
    "accounting.summary_table": "Monthly Summary Table",
    "accounting.table_month": "Month",
    "accounting.table_sales": "Sales",
    "accounting.table_cost": "Cost",
    "accounting.table_gross": "Gross",
    "accounting.table_net": "Net",
    "accounting.total": "Total",

    // Reports
    "reports.title": "Reports",
    "reports.subtitle": "Business analytics and reports",
    "reports.overview": "Overview",
    "reports.shift_reports": "Shift Reports",
    "reports.cashier_board": "Cashier Board",
    "reports.peak_hours": "Peak Hours",
    "reports.ai_forecast": "AI Forecast",
    "reports.total_revenue": "Total Revenue",
    "reports.total_tax": "Total Tax Collected",
    "reports.total_purchases": "Total Purchases",
    "reports.net_profit": "Net Profit (Est.)",
    "reports.sales_vs_purchases": "Sales vs Purchases",
    "reports.gst_breakdown": "GST Rate Breakdown",
    "reports.gstr_summary": "GSTR Summary",
    "reports.total_shifts": "Total Shifts",
    "reports.shift_history_empty": "No shift history yet",
    "reports.shift_history_empty_sub": "Open the POS terminal, start a shift, and close it to see reports here.",
    "reports.cashier_leaderboard": "Cashier Performance Leaderboard",
    "reports.cashier_leaderboard_sub": "Ranked by total sales volume across all shifts",
    "reports.cashier_no_data": "No cashier data yet",
    "reports.cashier_no_data_sub": "Start and close shifts in the POS to see leaderboard.",
    "reports.peak_business_hours": "Peak Business Hours",
    "reports.peak_hours_sub": "Invoice frequency and revenue heatmap by hour of day",
    "reports.bills_per_hour": "Bills per Hour (6am  11pm)",
    "reports.heatmap_title": "Transaction Density Heatmap",
    "reports.ai_sales_forecast": "AI Sales Forecast",
    "reports.ai_forecast_sub": "7-day rolling average + next 7-day revenue prediction",
    "reports.sales_trend_forecast": "30-Day Sales Trend + Forecast",
    "reports.trend_forecast_sub": "Actual sales (amber) · Moving average (blue) · AI forecast (dashed)",
    "reports.revenue_forecast_7day": "7-Day Revenue Forecast",
    "reports.ai_predicted": "AI Predicted",
    "reports.sales": "Sales",
    "reports.purchases": "Purchases",
    "reports.tax": "Tax",
    "reports.bills": "bills",
    "reports.traffic_no": "No traffic",
    "reports.traffic_low": "Low",
    "reports.traffic_med": "Medium",
    "reports.traffic_high": "High",
    "reports.traffic_peak": "Peak",

    // Branches
    "branches.title": "Branch Management",
    "branches.subtitle": "Manage your retail outlets",
    "branches.add": "Add Branch",
    "branches.branch_name": "Branch Name",
    "branches.branch_code": "Branch Code",
    "branches.branch_type": "Branch Type",
    "branches.total_branches": "Total Branches",
    "branches.stores": "Stores",
    "branches.warehouses": "Warehouses",
    "branches.hq_kiosks": "HQ / Kiosks",
    "branches.no_branches": "No Branches Yet",
    "branches.create_first": "Add your first branch",
    "branches.basic_info": "Basic Info",
    "branches.contact": "Contact",
    "branches.gst_billing": "GST & Billing",
    "branches.active_outlet": "Active Outlet",
    "branches.create_branch": "Create Branch",
    "branches.update_branch": "Update Branch",
    "branches.remove": "Remove",

    // GST
    "gst.title": "GST Filing",
    "gst.subtitle": "File your GST returns",

    // Barcode
    "barcode.title": "Barcode Generator",
    "barcode.subtitle": "Generate and print barcodes",

    // Subscription
    "subscription.title": "Upgrade to Pro",
    "subscription.subtitle": "Unlock premium features",

    // Warehouse
    "warehouse.title": "Warehouse Hub",
    "warehouse.subtitle": "Manage warehouse operations",
    "warehouse.header_title": "Warehouse & Purchase Hub",
    "warehouse.sap_badge": "SAP Retail Hub",
    "warehouse.header_desc": "Vendor directory, automated low-stock PO compiler, batch expiry controls, structural rack locations, and GRN processing.",
    "warehouse.register_vendor": "Register Vendor",
    "warehouse.auto_compile": "Auto-Compile Reorders",
    "warehouse.log_new_batch": "Log New Batch",
    "warehouse.active_vendors": "Active Vendors",
    "warehouse.live_synced": "Live Synced",
    "warehouse.low_stock_items": "Low Stock Items",
    "warehouse.under_threshold": "under threshold",
    "warehouse.expiring_stock": "Expiring Stock",
    "warehouse.days_left_60": "days left < 60",
    "warehouse.expired_batches": "Expired Batches",
    "warehouse.needs_disposal": "Needs Disposal",
    "warehouse.tab_vendors": "Vendors",
    "warehouse.tab_rack": "Rack Layout",
    "warehouse.tab_expiry": "Expiry Log",
    "warehouse.tab_po": "PO & GRN",
    "warehouse.search_vendor_placeholder": "Search Vendor Name, Code, GSTIN...",
    "warehouse.search_product_placeholder": "Search Product SKU, Name, Barcode...",
    "warehouse.search_batch_placeholder": "Search Batch ID, Product Name...",
    "warehouse.auto_supplier_reorders": "Automated Supplier Reorders",
    "warehouse.auto_po_desc": "Let SAP Demand forecasting scan low-stock inventories and group them into formal drafts.",
    "warehouse.compile_low_stock_pos": "Compile Low Stock POs",
    "warehouse.active_pos_ledger": "Active Purchase & Receipt Orders",
    "warehouse.status_good": "Good Stock",
    "warehouse.status_expired": "EXPIRED",
    "warehouse.status_expiring": "EXPIRING SOON",
    "warehouse.unassigned": "Unassigned",
    "warehouse.reassign_location": "Reassign Location",
    "warehouse.process_grn": "Process GRN",
    "warehouse.print_po": "Print PO",
    "warehouse.edit_vendor": "Edit Vendor Profile",
    "warehouse.register_new_vendor": "Register New Vendor",
    "warehouse.vendor_desc": "Add structural parameters for the supplier, like billing credit terms and tax tags.",
    "warehouse.vendor_name": "Vendor Name *",
    "warehouse.vendor_code": "Vendor Code *",
    "warehouse.phone_number": "Phone Number",
    "warehouse.email_address": "Email Address",
    "warehouse.warehouse_address": "Office / Warehouse Address",
    "warehouse.vendor_gstin": "Vendor GSTIN",
    "warehouse.terms": "Terms",
    "warehouse.credit_limit": "Credit limit ()",
    "warehouse.save_supplier_profile": "Save Supplier Profile",
    "warehouse.configure_structural_location": "Configure Structural Location",
    "warehouse.rack_desc": "Map the product to a physical layout section inside the warehouse.",
    "warehouse.aisle": "Aisle (e.g. Aisle 3)",
    "warehouse.rack": "Rack Code (e.g. Rack B)",
    "warehouse.shelf": "Shelf (e.g. Shelf 2)",
    "warehouse.bin": "Bin ID (Optional)",
    "warehouse.assign_section": "Assign Section",
    "warehouse.log_inventory_batch": "Log Inventory Batch",
    "warehouse.batch_desc": "Track perishable or wholesale products by batch IDs and expiry limits.",
    "warehouse.select_product": "Select Product",
    "warehouse.batch_number": "Batch Number / ID *",
    "warehouse.qty_received": "Quantity Received *",
    "warehouse.mfg_date": "Mfg Date",
    "warehouse.expiry_date": "Expiry Date *",
    "warehouse.register_batch": "Register Batch",
    "warehouse.grn_title": "Goods Receipt Note (GRN)",
    "warehouse.grn_desc": "Verify items arriving from supplier. Received quantities will automatically post to active stock.",
    "warehouse.supplier_invoice": "Supplier Invoice / Bill No *",
    "warehouse.received_checklist": "Received Items Checklist",
    "warehouse.received_qty": "Received Qty",
    "warehouse.damaged_qty": "Damaged Qty",
    "warehouse.assign_batch_id": "Assign Batch ID",
    "warehouse.batch_expiry": "Batch Expiry",
    "warehouse.verify_receipt_post_stock": "Verify Receipt & Post Stock",
    "warehouse.ordered": "Ordered:",
    "warehouse.units": "units",
    "warehouse.units_cap": "Units",
    "warehouse.expired_label": "Expired",
    "warehouse.days_remaining": "days remaining",
    "warehouse.live_stock_map": "Live Stock Map",
    "warehouse.in_stock": "In Stock (HQ)",
    "warehouse.structural_aisle": "Structural Aisle",
    "warehouse.rack_section": "Rack Section",
    "warehouse.shelf_index": "Shelf Index",
    "warehouse.expiry_date_label": "Expiry Date",
    "warehouse.shelf_life_remaining": "Shelf Life Remaining",
    "warehouse.status": "Status",
    "warehouse.po_number": "PO Number",
    "warehouse.supplier_name": "Supplier Name",
    "warehouse.items_ordered": "Items Ordered",
    "warehouse.total_value": "Total Value",
    "warehouse.creation_date": "Creation Date",
    "warehouse.actions": "Actions",

    // Stock Transfer
    "stock_transfer.title": "Stock Transfer",
    "stock_transfer.subtitle": "Transfer stock between branches with real-time synchronization",
    "stock_transfer.new_transfer": "New Transfer",
    "stock_transfer.total_transfers": "Total Transfers",
    "stock_transfer.this_session": "This session",
    "stock_transfer.completed": "Completed",
    "stock_transfer.success_transferred": "Successfully transferred",
    "stock_transfer.branches_connected": "Branches Connected",
    "stock_transfer.active_locations": "Active locations",
    "stock_transfer.recent_transfers": "Recent Transfers",
    "stock_transfer.no_transfers": "No transfers yet",
    "stock_transfer.transfers_in_history": "transfer(s) in history",
    "stock_transfer.create_transfer": "Create Stock Transfer",
    "stock_transfer.product_id": "Product ID",
    "stock_transfer.from_branch": "From Branch",
    "stock_transfer.to_branch": "To Branch",
    "stock_transfer.quantity": "Quantity",
    "stock_transfer.notes": "Notes (Optional)",
    "stock_transfer.enter_qty": "Enter quantity",
    "stock_transfer.transfer_stock": "Transfer Stock",
    "stock_transfer.how_it_works": "How Stock Transfer Works",
    "stock_transfer.help_bullet_1": "Enter product ID and select source and destination branches",
    "stock_transfer.help_bullet_2": "System automatically deducts from source and adds to destination branch",
    "stock_transfer.help_bullet_3": "All transfers are logged for audit trail and inventory tracking",
    "stock_transfer.help_bullet_4": "Stock updates propagate across all branches within milliseconds",
    "stock_transfer.help_bullet_5": "Perfect for branch rebalancing and new store stocking",
    "stock_transfer.toast_fill_required": "Please fill all required fields",
    "stock_transfer.toast_different_branches": "Source and destination branches must be different",
    "stock_transfer.toast_insufficient_stock": "Insufficient stock in source branch",
    "stock_transfer.toast_transfer_success": "Stock transferred successfully!",
    "stock_transfer.toast_transfer_failed": "Transfer failed: ",
    "stock_transfer.exceeds_stock": "Exceeds available stock",
    "stock_transfer.available": "Available:",

    // POS
    "pos.title": "Point of Sale",
    "pos.barcode": "Barcode Mode",
    "pos.search_placeholder": "Search item, HSN code, or SKU...",
    "pos.scan_placeholder": "Scan Barcode Now...",
    "pos.table": "Table:",
    "pos.size": "Size:",
    "pos.color": "Color:",
    "pos.cart_empty": "Cart is empty",
    "pos.cart_sub": "Scan barcodes or touch products on the left",
    "pos.discount": "Discount Apply",
    "pos.payment_method": "Payment Method",
    "pos.subtotal": "Subtotal",
    "pos.tax": "Tax CGST + SGST",
    "pos.grand_total": "GRAND TOTAL",
    "pos.park_bill": "Park Bill",
    "pos.pay_print": "PAY & PRINT (F4)",
    "pos.customer_acc": "Customer Account",
    "pos.add_new": "ADD NEW",
    "pos.billing_type": "Billing Type",
    "pos.send_kitchen": "Send to Kitchen (KOT)",
    "pos.weight_label": "Enter Weight (Kg)",
    "pos.variants_label": "Select Variants",
    "pos.expiry_label": "Exp Date",
    "pos.cash": "Cash",
    "pos.card": "Card",
    "pos.upi": "UPI",
    "pos.split": "Split Payment",
    "pos.credit": "Credit",
    "pos.qty": "Qty",
    "pos.price": "Price",
    "pos.new_sale": "New Sale",
    "pos.return_sale": "Return / Refund",
    "pos.cashier": "Cashier",
    "pos.total_transactions": "Total Transactions",
    "pos.billing_history": "Billing History",
    "pos.billing_history_subtitle": "View, reprint & manage all invoices",
    "pos.invoices_log": "Invoices Log",
    "pos.parked_bills": "Parked Bills",
    "pos.today_bills": "Today's Bills",
    "pos.today_revenue": "Today's Revenue",
    "pos.total_bills": "Total Bills",
    "pos.search_invoice_placeholder": "Search invoice no. or customer name...",
    "pos.no_invoices_found": "No invoices found",
    "pos.adjust_filters": "Try adjusting the filters",
    "pos.walk_in_customer": "Walk-in Customer",
    "pos.walk_in": "Walk-in",
    "pos.default": "Default",
    "pos.add_customer_btn": "Add",
    "pos.clear_selection": "Clear selection",
    "pos.edit_customer": "Edit customer",
    "pos.open_shift": "Open Shift",
    "pos.close_shift": "Close Shift",
    "pos.starting_cash": "Starting Cash",
    "pos.counter_number": "Counter Number",
    "pos.cashier_name": "Cashier Name",


    // Metrics
    "metric.total_sales": "Total Sales",
    "metric.gross_profit": "Gross Profit",
    "metric.net_profit": "Net Profit",
    "metric.gst_collected": "GST Collected",
    "metric.outstanding": "Outstanding",
    "metric.purchases": "Purchases",
    "metric.expenses": "Expenses",
    "metric.customers": "Customers",
    "metric.products": "Products",
    "metric.loan_debt": "Loan Debt",
    "metric.sales_vs_expenses": " Sales vs Expenses (Daily)",
    "metric.payment_status": " Payment Status",
    "metric.monthly_pl": " Monthly P&L (6 Months)",
    "metric.expense_breakdown": " Expense Breakdown",
    "metric.profit_trend": "Profit Trend",
    "metric.recent_invoices": " Recent Invoices",
    "metric.stock_alerts": "️ Stock Alerts",
    "metric.top_customers": "⭐ Top Customers",

    // Voice
    "voice.welcome": "Welcome back!",
    "voice.cart_added": "Product added.",
    "voice.cart_removed": "Item removed from cart.",
    "voice.checkout_success": "Bill paid and printed successfully.",
    "voice.bill_parked": "Bill has been parked.",
    "voice.scan_enabled": "Barcode scanning enabled.",
    "voice.scan_disabled": "Barcode scanning disabled.",
    "voice.kot_sent": "Order sent to kitchen.",
  },
  hi: {
    // Nav
    "nav.dashboard": "डैशबोर्ड",
    "nav.pos": "क्विक POS",
    "nav.invoices": "बिल / इनवॉइस",
    "nav.purchases": "खरीदारी",
    "nav.waybills": "ई-वे बिल",
    "nav.inventory": "स्टॉक / इन्वेंटरी",
    "nav.customers": "ग्राहक",
    "nav.expenses": "खर्चे",
    "nav.accounting": "खाता-बही",
    "nav.loans": "लोन / कर्ज़",
    "nav.barcode": "बारकोड",
    "nav.gstfiling": "GST फाइलिंग",
    "nav.reports": "रिपोर्ट",
    "nav.aiinsights": "AI सुझाव",
    "nav.settings": "सेटिंग्स",
    "nav.upgrade": "अपग्रेड",
    "nav.logout": "लॉगआउट",
    "nav.branches": "शाखाएं",
    "nav.invsync": "इन्वेंटरी सिंक",
    "nav.stocktransfer": "स्टॉक ट्रांसफर",
    "nav.warehouse": "वेयरहाउस",
    "nav.enterprise_intel": "एंटरप्राइज़",
    "nav.finance": "वित्त हब",
    "nav.auditLogs": "ऑडिट लॉग्स",
    "nav.manufacturing": "उत्पादन ईआरपी",
    "nav.hrms": "HRMS और पेरोल",
    "nav.supermarket_counters": "काउंटर प्रबंधन",
    "nav.supermarket_offers": "ऑफ़र इंजन",
    "nav.supermarket_loyalty": "लॉयल्टी प्रोग्राम",
    "nav.supermarket_expiry": "समाप्ति प्रबंधन",
    "nav.supermarket_reports": "विभाग रिपोर्ट",

    // Common
    "common.save": "सेव करें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.add": "जोड़ें",
    "common.update": "अपडेट करें",
    "common.search": "खोजें",
    "common.filter": "फ़िल्टर",
    "common.export": "निर्यात करें",
    "common.import": "आयात करें",
    "common.print": "प्रिंट करें",
    "common.download": "डाउनलोड करें",
    "common.close": "बंद करें",
    "common.confirm": "पुष्टि करें",
    "common.yes": "हाँ",
    "common.no": "नहीं",
    "common.back": "वापस",
    "common.next": "आगे",
    "common.submit": "जमा करें",
    "common.loading": "लोड हो रहा है...",
    "common.saving": "सेव हो रहा है...",
    "common.no_data": "कोई डेटा नहीं मिला",
    "common.view_all": "सभी देखें",
    "common.actions": "कार्रवाई",
    "common.status": "स्थिति",
    "common.date": "तारीख",
    "common.amount": "राशि",
    "common.total": "कुल",
    "common.name": "नाम",
    "common.phone": "फ़ोन",
    "common.email": "ईमेल",
    "common.address": "पता",
    "common.category": "श्रेणी",
    "common.type": "प्रकार",
    "common.active": "सक्रिय",
    "common.all": "सभी",
    "common.paid": "भुगतान हुआ",
    "common.unpaid": "बकाया",
    "common.partial": "आंशिक भुगतान",
    "common.pending": "लंबित",
    "common.completed": "पूर्ण",
    "common.details": "विवरण",
    "common.from": "से",
    "common.to": "तक",
    "common.today": "आज",
    "common.this_month": "इस महीने",
    "common.this_year": "इस साल",

    // Greetings
    "greeting.namaste": "नमस्ते",
    "dashboard.title": "डैशबोर्ड",
    "dashboard.subtitle": "व्यापार की पूरी जानकारी एक नज़र में",
    "dashboard.welcome": "वापस स्वागत है",
    "dashboard.quick_actions": "त्वरित कार्रवाई",
    "dashboard.create_invoice": "नया बिल बनाएं",
    "dashboard.add_product": "उत्पाद जोड़ें",
    "dashboard.add_customer": "ग्राहक जोड़ें",
    "dashboard.new_purchase": "नई खरीदारी",
    "dashboard.view_reports": "रिपोर्ट देखें",
    "dashboard.recent_activity": "हालिया गतिविधि",
    "dashboard.business_summary": "व्यापार सारांश",

    // Settings
    "settings.title": "️ सेटिंग्स",
    "settings.subtitle": "अपने व्यापार की प्रोफ़ाइल सेट करें",
    "settings.shop_name": "दुकान / व्यापार का नाम",
    "settings.business_type": "व्यापार का प्रकार",
    "settings.gst_number": "GST नंबर",
    "settings.pan_number": "PAN नंबर",
    "settings.phone": "फ़ोन नंबर",
    "settings.email": "ईमेल पता",
    "settings.address": "व्यापार का पता",
    "settings.city": "शहर",
    "settings.state": "राज्य",
    "settings.pincode": "पिनकोड",
    "settings.logo": "व्यापार का लोगो",
    "settings.signature": "डिजिटल हस्ताक्षर",
    "settings.save_settings": "सेटिंग्स सेव करें",
    "settings.general": "सामान्य",
    "settings.branding": "ब्रांडिंग",
    "settings.billing": "बिलिंग",
    "settings.printer_settings": "प्रिंटर सेटिंग्स",
    "settings.bank_details": "बैंक खाता विवरण",

    // Inventory
    "inventory.title": "इन्वेंटरी / स्टॉक",
    "inventory.subtitle": "अपने उत्पाद और स्टॉक प्रबंधित करें",
    "inventory.add_product": "उत्पाद जोड़ें",
    "inventory.edit_product": "उत्पाद संपादित करें",
    "inventory.product_name": "उत्पाद का नाम",
    "inventory.selling_price": "बिक्री मूल्य",
    "inventory.purchase_price": "खरीद मूल्य",
    "inventory.stock": "स्टॉक",
    "inventory.current_stock": "वर्तमान स्टॉक",
    "inventory.min_stock": "न्यूनतम स्टॉक",
    "inventory.gst_rate": "GST दर",
    "inventory.hsn_code": "HSN कोड",
    "inventory.barcode": "बारकोड",
    "inventory.category": "श्रेणी",
    "inventory.unit": "इकाई",
    "inventory.stock_value": "स्टॉक मूल्य",
    "inventory.in_stock": "स्टॉक में",
    "inventory.low_stock": "कम स्टॉक",
    "inventory.out_of_stock": "स्टॉक ख़त्म",
    "inventory.total_products": "कुल उत्पाद",
    "inventory.total_value": "कुल मूल्य",
    "inventory.stock_adjust": "स्टॉक समायोजन",
    "inventory.stock_in": "स्टॉक इन",
    "inventory.stock_out": "स्टॉक आउट",
    "inventory.set_exact": "सटीक सेट करें",
    "inventory.quantity": "मात्रा",
    "inventory.reason": "कारण",
    "inventory.purchase_grn": "खरीद / GRN",
    "inventory.customer_return": "ग्राहक से वापसी",
    "inventory.transfer_in": "स्टॉक ट्रांसफर इन",
    "inventory.opening_stock": "शुरुआती स्टॉक",
    "inventory.sale_billing": "बिक्री / बिलिंग",
    "inventory.damage_wastage": "नुकसान / बर्बादी",
    "inventory.transfer_out": "स्टॉक ट्रांसफर आउट",
    "inventory.expired": "समय सीमा समाप्त",
    "inventory.physical_count": "भौतिक गिनती",
    "inventory.audit_correction": "ऑडिट सुधार",
    "inventory.other": "अन्य",
    "inventory.after": "बाद में",
    "inventory.change": "बदलाव",
    "inventory.bulk_select": "एकाधिक",
    "inventory.delete_selected": "चुने हुए हटाएं",
    "inventory.no_products": "कोई उत्पाद नहीं मिला",
    "inventory.add_first": "शुरू करने के लिए अपना पहला उत्पाद जोड़ें",
    "inventory.sort_by": "क्रम",
    "inventory.all_categories": "सभी श्रेणियां",
    "inventory.all_stock": "सभी स्टॉक",
    "inventory.stock_status": "स्टॉक स्थिति",
    "inventory.showing": "दिखा रहे हैं",
    "inventory.of": "में से",
    "inventory.products": "उत्पाद",
    "inventory.branch_view": "शाखा स्टॉक दृश्य",
    "inventory.global_catalog": "वैश्विक कैटलॉग",

    // Invoices
    "invoices.title": "बिल / इनवॉइस",
    "invoices.subtitle": "अपने बिक्री बिल प्रबंधित करें",
    "invoices.create": "नया बिल बनाएं",
    "invoices.invoice_number": "बिल नंबर",
    "invoices.customer_name": "ग्राहक का नाम",
    "invoices.invoice_date": "बिल की तारीख",
    "invoices.due_date": "देय तिथि",
    "invoices.grand_total": "कुल राशि",
    "invoices.paid": "भुगतान हो गया",
    "invoices.unpaid": "बकाया",
    "invoices.overdue": "अतिदेय",
    "invoices.no_invoices": "अभी कोई बिल नहीं",
    "invoices.total_invoices": "कुल इनवॉइस",
    "invoices.sale_invoice": "बिक्री इनवॉइस",
    "invoices.credit_note": "क्रेडिट नोट",
    "invoices.debit_note": "डेबिट नोट",
    "invoices.credit_notes": "क्रेडिट नोट्स",
    "invoices.debit_notes": "डेबिट नोट्स",
    "invoices.all": "सभी",
    "invoices.search_placeholder": "इनवॉइस या ग्राहक खोजें...",
    "invoices.toast_saved": "इनवॉइस सहेज ली गई!",
    "invoices.toast_updated": "इनवॉइस अपडेट हो गई!",
    "invoices.toast_created": "इनवॉइस बन गई!",
    "invoices.toast_pdf_generating": "PDF बिल बनाया और अपलोड किया जा रहा है...",
    "invoices.toast_whatsapp_opened": "WhatsApp खुल गया!",
    "invoices.toast_pdf_failed": "PDF साझा करने में विफल: ",
    "invoices.interstate": "अंतर-राज्यीय",
    "invoices.due": "देय",
    "invoices.days_overdue": "दिनों की देरी",

    // Customers
    "customers.title": "ग्राहक",
    "customers.subtitle": "अपना ग्राहक डेटाबेस प्रबंधित करें",
    "customers.add": "ग्राहक जोड़ें",
    "customers.name": "ग्राहक का नाम",
    "customers.phone": "फ़ोन नंबर",
    "customers.outstanding": "बकाया राशि",
    "customers.no_customers": "कोई ग्राहक नहीं मिला",
    "customers.contact_person": "संपर्क व्यक्ति का नाम",
    "customers.gstin": "GSTIN",
    "customers.address": "पता",
    "customers.city": "शहर",
    "customers.state": "राज्य",
    "customers.pincode": "पिनकोड",
    "customers.credit_limit": "उधार सीमा",
    "customers.category": "श्रेणी",
    "customers.notes": "टिप्पणियाँ",
    "customers.edit": "ग्राहक संपादित करें",
    "customers.delete_confirm": "क्या आप इस ग्राहक को हटाना चाहते हैं?",
    "customers.search_placeholder": "ग्राहकों को खोजें...",
    "customers.business_name": "ग्राहक / व्यवसाय का नाम",
    "customers.toast_added": "ग्राहक जोड़ दिया गया!",
    "customers.toast_updated": "ग्राहक अपडेट हो गया!",
    "customers.toast_deleted": "ग्राहक हटा दिया गया",

    // Purchases
    "purchases.title": "खरीदारी",
    "purchases.subtitle": "विक्रेता खरीदारी और GRN प्रबंधित करें",
    "purchases.add": "नई खरीदारी",
    "purchases.vendor_name": "विक्रेता का नाम",
    "purchases.total_amount": "कुल राशि",
    "purchases.no_purchases": "अभी कोई खरीदारी नहीं",
    "purchases.purchase_entries_count": "खरीद प्रविष्टियां दर्ज की गईं",
    "purchases.portal_header": "खरीद प्रविष्टि पोर्टल",
    "purchases.gst_compliant": "GST अनुरूप",
    "purchases.edit_entry": "खरीद प्रविष्टि संपादित करें",
    "purchases.new_entry": "नई खरीद प्रविष्टि",
    "purchases.vendor_details": "विक्रेता और इनवॉइस विवरण",
    "purchases.vendor_name_label": "विक्रेता का नाम *",
    "purchases.vendor_phone_label": "विक्रेता का फ़ोन",
    "purchases.vendor_gstin_label": "विक्रेता GSTIN",
    "purchases.date_label": "खरीद की तारीख",
    "purchases.invoice_no_label": "विक्रेता इनवॉइस नंबर",
    "purchases.items_cart": "खरीदे गए उत्पाद और कार्ट",
    "purchases.search_placeholder": "बारकोड स्कैन करें या खोजने के लिए नाम टाइप करें...",
    "purchases.quick_add_product": "नया उत्पाद जोड़ें",
    "purchases.prev_purchased": "इस विक्रेता से पहले खरीदे गए उत्पाद:",
    "purchases.product_details": "उत्पाद विवरण",
    "purchases.qty": "मात्रा",
    "purchases.buy_price": "खरीद मूल्य",
    "purchases.gst_pct": "GST %",
    "purchases.no_items": "अभी तक कोई उत्पाद नहीं जोड़ा गया है। ऊपर से उत्पाद खोजें या नया जोड़ें।",
    "purchases.payment_terms": "भुगतान की शर्तें",
    "purchases.payment_status": "भुगतान की स्थिति",
    "purchases.amount_paid": "भुगतान की गई राशि",
    "purchases.due_amount": "बकाया राशि",
    "purchases.payment_mode": "भुगतान का प्रकार",
    "purchases.due_date": "नियत तारीख (कब भुगतान करना है) *",
    "purchases.remarks": "टिप्पणी / नोट्स",
    "purchases.grand_total": "कुल राशि",
    "purchases.save_order": "खरीद सहेजें",
    "purchases.paid": "पूर्ण भुगतान",
    "purchases.partial": "आंशिक भुगतान",
    "purchases.unpaid": "बकाया / ड्यू",
    "purchases.cash": "नकद (Cash)",
    "purchases.upi": "UPI / स्कैनर",
    "purchases.bank": "बैंक ट्रांसफर",
    "purchases.credit": "आपूर्तिकर्ता क्रेडिट",
    "purchases.due_label": "बकाया:",
    "purchases.pay_by_label": "भुगतान की तारीख:",
    "purchases.toast_created": "खरीद प्रविष्टि सहेजी गई और स्टॉक अपडेट हो गया!",
    "purchases.toast_updated": "खरीद प्रविष्टि अपडेट हो गई!",

    // Expenses
    "expenses.title": "खर्चे",
    "expenses.subtitle": "अपने व्यापार के खर्चे ट्रैक करें",
    "expenses.add": "खर्चा जोड़ें",
    "expenses.amount": "राशि",
    "expenses.category": "श्रेणी",
    "expenses.no_expenses": "कोई खर्चा दर्ज नहीं",
    "expenses.total_this_month": "इस महीने कुल खर्चा",
    "expenses.title_tracker": "खर्चा ट्रैकर",
    "expenses.subtitle_tracker": "सभी व्यावसायिक खर्चों और परिचालन लागतों को ट्रैक करें",
    "expenses.total": "कुल खर्चे",
    "expenses.entries": "कुल प्रविष्टियां",
    "expenses.categories": "श्रेणियां",
    "expenses.breakdown": "श्रेणी विवरण",
    "expenses.search_placeholder": "खर्चों को खोजें...",
    "expenses.all_categories": "सभी श्रेणियां",
    "expenses.edit": "खर्चा संपादित करें",
    "expenses.gst_amount": "GST राशि",
    "expenses.paid_to": "भुगतान किया",
    "expenses.payment_mode": "भुगतान का प्रकार",
    "expenses.ref_no": "संदर्भ संख्या",

    // Loans
    "loans.title": "लोन / कर्ज़",
    "loans.subtitle": "व्यापार लोन और EMI प्रबंधित करें",
    "loans.add": "लोन जोड़ें",
    "loans.lender_name": "ऋणदाता का नाम",
    "loans.principal": "मूल राशि",
    "loans.outstanding": "बकाया राशि",
    "loans.interest_rate": "ब्याज दर",
    "loans.active": "सक्रिय",
    "loans.closed": "बंद",
    "loans.no_loans": "कोई लोन नहीं मिला",

    // Accounting
    "accounting.title": "खाता-बही",
    "accounting.subtitle": "लाभ-हानि, बैलेंस शीट",
    "accounting.profit_loss": "लाभ-हानि",
    "accounting.balance_sheet": "बैलेंस शीट",
    "accounting.revenue": "आय",
    "accounting.gross_profit": "सकल लाभ",
    "accounting.net_profit": "शुद्ध लाभ",
    "accounting.title_page": "अकाउंटिंग और लाभ-हानि",
    "accounting.subtitle_page": "पूर्ण वित्तीय अवलोकन और लाभ/हानि विश्लेषण",
    "accounting.total_revenue": "कुल राजस्व (बिक्री)",
    "accounting.total_purchases": "कुल खरीद",
    "accounting.total_expenses": "कुल खर्च",
    "accounting.gst_collected": "एकत्रित जीएसटी",
    "accounting.profit_margin": "लाभ मार्जिन",
    "accounting.loan_liability": "ऋण देनदारी",
    "accounting.monthly_chart_title": "मासिक राजस्व और लाभ",
    "accounting.profit_trend": "लाभ का रुझान",
    "accounting.summary_table": "मासिक सारांश तालिका",
    "accounting.table_month": "महीना",
    "accounting.table_sales": "बिक्री",
    "accounting.table_cost": "लागत",
    "accounting.table_gross": "सकल",
    "accounting.table_net": "शुद्ध",
    "accounting.total": "कुल",

    // Reports
    "reports.title": "रिपोर्ट",
    "reports.subtitle": "व्यापार विश्लेषण और रिपोर्ट",
    "reports.overview": "अवलोकन",
    "reports.shift_reports": "शिफ्ट रिपोर्ट",
    "reports.cashier_board": "कैशियर बोर्ड",
    "reports.peak_hours": "पीक ऑवर्स",
    "reports.ai_forecast": "AI पूर्वानुमान",
    "reports.total_revenue": "कुल राजस्व",
    "reports.total_tax": "कुल टैक्स संग्रह",
    "reports.total_purchases": "कुल खरीदारी",
    "reports.net_profit": "शुद्ध लाभ (अनु.)",
    "reports.sales_vs_purchases": "बिक्री बनाम खरीदारी",
    "reports.gst_breakdown": "GST दर विवरण",
    "reports.gstr_summary": "GSTR सारांश",
    "reports.total_shifts": "कुल शिफ्ट",
    "reports.shift_history_empty": "अभी कोई शिफ्ट इतिहास नहीं है",
    "reports.shift_history_empty_sub": "रिपोर्ट देखने के लिए POS टर्मिनल खोलें, शिफ्ट शुरू करें और उसे बंद करें।",
    "reports.cashier_leaderboard": "कैशियर प्रदर्शन लीडरबोर्ड",
    "reports.cashier_leaderboard_sub": "सभी शिफ्टों में कुल बिक्री मात्रा के आधार पर रैंक किया गया",
    "reports.cashier_no_data": "अभी कोई कैशियर डेटा नहीं है",
    "reports.cashier_no_data_sub": "लीडरबोर्ड देखने के लिए POS में शिफ्ट शुरू और बंद करें।",
    "reports.peak_business_hours": "पीक बिजनेस ऑवर्स",
    "reports.peak_hours_sub": "दिन के घंटे के हिसाब से इनवॉइस आवृत्ति और राजस्व हीटमैप",
    "reports.bills_per_hour": "प्रति घंटा बिल (सुबह 6 - रात 11)",
    "reports.heatmap_title": "लेन-देन घनत्व हीटमैप",
    "reports.ai_sales_forecast": "AI बिक्री पूर्वानुमान",
    "reports.ai_forecast_sub": "7-दिवसीय रोलिंग औसत + अगले 7-दिवसीय राजस्व पूर्वानुमान",
    "reports.sales_trend_forecast": "30-दिवसीय बिक्री रुझान + पूर्वानुमान",
    "reports.trend_forecast_sub": "वास्तविक बिक्री (एम्बर) · मूविंग एवरेज (नीला) · AI पूर्वानुमान (डैश)",
    "reports.revenue_forecast_7day": "7-दिवसीय राजस्व पूर्वानुमान",
    "reports.ai_predicted": "AI पूर्वानुमानित",
    "reports.sales": "बिक्री",
    "reports.purchases": "खरीदारी",
    "reports.tax": "टैक्स",
    "reports.bills": "बिल",
    "reports.traffic_no": "कोई ट्रैफ़िक नहीं",
    "reports.traffic_low": "कम",
    "reports.traffic_med": "मध्यम",
    "reports.traffic_high": "उच्च",
    "reports.traffic_peak": "पीक",

    // Branches
    "branches.title": "शाखा प्रबंधन",
    "branches.subtitle": "अपनी दुकानों और शाखाओं का प्रबंधन करें",
    "branches.add": "शाखा जोड़ें",
    "branches.branch_name": "शाखा का नाम",
    "branches.branch_code": "शाखा कोड",
    "branches.branch_type": "शाखा प्रकार",
    "branches.total_branches": "कुल शाखाएं",
    "branches.stores": "दुकानें",
    "branches.warehouses": "गोदाम",
    "branches.hq_kiosks": "मुख्यालय / काउंटर",
    "branches.no_branches": "अभी कोई शाखा नहीं",
    "branches.create_first": "मल्टी-आउटलेट प्रबंधन शुरू करने के लिए पहली शाखा जोड़ें",
    "branches.basic_info": "मूल जानकारी",
    "branches.contact": "संपर्क",
    "branches.gst_billing": "GST और बिलिंग",
    "branches.active_outlet": "सक्रिय आउटलेट",
    "branches.create_branch": "शाखा बनाएं",
    "branches.update_branch": "शाखा अपडेट करें",
    "branches.remove": "हटाएं",

    // GST
    "gst.title": "GST फाइलिंग",
    "gst.subtitle": "अपनी GST रिटर्न फाइल करें",

    // Barcode
    "barcode.title": "बारकोड जनरेटर",
    "barcode.subtitle": "बारकोड बनाएं और प्रिंट करें",

    // Subscription
    "subscription.title": "प्रो में अपग्रेड करें",
    "subscription.subtitle": "प्रीमियम सुविधाएं अनलॉक करें",

    // Warehouse
    "warehouse.title": "वेयरहाउस हब",
    "warehouse.subtitle": "गोदाम संचालन प्रबंधित करें",
    "warehouse.header_title": "वेयरहाउस और खरीद हब",
    "warehouse.sap_badge": "एसएपी रिटेल हब",
    "warehouse.header_desc": "विक्रेता निर्देशिका, स्वचालित कम-स्टॉक पीओ कंपाइलर, बैच समाप्ति नियंत्रण, संरचनात्मक रैक स्थान और जीआरएन प्रोसेसिंग।",
    "warehouse.register_vendor": "विक्रेता पंजीकृत करें",
    "warehouse.auto_compile": "स्वचालित पुन:आदेश कंपाइल",
    "warehouse.log_new_batch": "नया बैच दर्ज करें",
    "warehouse.active_vendors": "सक्रिय विक्रेता",
    "warehouse.live_synced": "लाइव सिंक किया गया",
    "warehouse.low_stock_items": "कम स्टॉक आइटम",
    "warehouse.under_threshold": "सीमा के तहत",
    "warehouse.expiring_stock": "समाप्त होने वाला स्टॉक",
    "warehouse.days_left_60": "दिन शेष < 60",
    "warehouse.expired_batches": "समाप्त बैच",
    "warehouse.needs_disposal": "निपटान की आवश्यकता",
    "warehouse.tab_vendors": "विक्रेता",
    "warehouse.tab_rack": "रैक लेआउट",
    "warehouse.tab_expiry": "समाप्ति लॉग",
    "warehouse.tab_po": "पीओ और जीआरएन",
    "warehouse.search_vendor_placeholder": "विक्रेता का नाम, कोड, जीएसटीआईएन खोजें...",
    "warehouse.search_product_placeholder": "उत्पाद SKU, नाम, बारकोड खोजें...",
    "warehouse.search_batch_placeholder": "बैच आईडी, उत्पाद का नाम खोजें...",
    "warehouse.auto_supplier_reorders": "स्वचालित आपूर्तिकर्ता पुन:आदेश",
    "warehouse.auto_po_desc": "एसएपी डिमांड फोरकास्टिंग को कम स्टॉक वाले इनवेंटरी को स्कैन करने दें और उन्हें ड्राफ्ट में समूहित करने दें।",
    "warehouse.compile_low_stock_pos": "कम स्टॉक वाले पीओ कंपाइल करें",
    "warehouse.active_pos_ledger": "सक्रिय खरीद और रसीद आदेश",
    "warehouse.status_good": "अच्छा स्टॉक",
    "warehouse.status_expired": "समाप्त",
    "warehouse.status_expiring": "जल्द समाप्त होने वाला",
    "warehouse.unassigned": "अनिर्दिष्ट",
    "warehouse.reassign_location": "स्थान पुन:निर्धारित करें",
    "warehouse.process_grn": "जीआरएन प्रोसेस करें",
    "warehouse.print_po": "पीओ प्रिंट करें",
    "warehouse.edit_vendor": "विक्रेता प्रोफ़ाइल संपादित करें",
    "warehouse.register_new_vendor": "नया विक्रेता पंजीकृत करें",
    "warehouse.vendor_desc": "आपूर्तिकर्ता के लिए संरचनात्मक पैरामीटर जोड़ें, जैसे बिलिंग क्रेडिट शर्तें और टैक्स टैग।",
    "warehouse.vendor_name": "विक्रेता का नाम *",
    "warehouse.vendor_code": "विक्रेता कोड *",
    "warehouse.phone_number": "फ़ोन नंबर",
    "warehouse.email_address": "ईमेल पता",
    "warehouse.warehouse_address": "कार्यालय / गोदाम का पता",
    "warehouse.vendor_gstin": "विक्रेता जीएसटीआईएन",
    "warehouse.terms": "शर्तें",
    "warehouse.credit_limit": "क्रेडिट सीमा ()",
    "warehouse.save_supplier_profile": "आपूर्तिकर्ता प्रोफ़ाइल सहेजें",
    "warehouse.configure_structural_location": "संरचनात्मक स्थान कॉन्फ़िगर करें",
    "warehouse.rack_desc": "उत्पाद को गोदाम के अंदर एक भौतिक लेआउट अनुभाग से मैप करें।",
    "warehouse.aisle": "गलियारा (जैसे गलियारा 3)",
    "warehouse.rack": "रैक कोड (जैसे रैक बी)",
    "warehouse.shelf": "शेल्फ (जैसे शेल्फ 2)",
    "warehouse.bin": "बिन आईडी (वैकल्पिक)",
    "warehouse.assign_section": "अनुभाग असाइन करें",
    "warehouse.log_inventory_batch": "इन्वेंटरी बैच दर्ज करें",
    "warehouse.batch_desc": "बैच आईडी और समाप्ति सीमाओं द्वारा खराब होने वाले या थोक उत्पादों को ट्रैक करें।",
    "warehouse.select_product": "उत्पाद चुनें",
    "warehouse.batch_number": "बैच नंबर / आईडी *",
    "warehouse.qty_received": "प्राप्त मात्रा *",
    "warehouse.mfg_date": "उत्पादन तिथि",
    "warehouse.expiry_date": "समाप्ति तिथि *",
    "warehouse.register_batch": "बैच पंजीकृत करें",
    "warehouse.grn_title": "सामान प्राप्ति नोट (GRN)",
    "warehouse.grn_desc": "आपूर्तिकर्ता से आने वाली वस्तुओं को सत्यापित करें। प्राप्त मात्रा स्वचालित रूप से स्टॉक में जोड़ दी जाएगी।",
    "warehouse.supplier_invoice": "आपूर्तिकर्ता चालान / बिल संख्या *",
    "warehouse.received_checklist": "प्राप्त वस्तुओं की सूची",
    "warehouse.received_qty": "प्राप्त मात्रा",
    "warehouse.damaged_qty": "क्षतिग्रस्त मात्रा",
    "warehouse.assign_batch_id": "बैच आईडी असाइन करें",
    "warehouse.batch_expiry": "बैच समाप्ति",
    "warehouse.verify_receipt_post_stock": "रसीद सत्यापित करें और स्टॉक पोस्ट करें",
    "warehouse.ordered": "आदेश दिया:",
    "warehouse.units": "इकाइयां",
    "warehouse.units_cap": "इकाइयां",
    "warehouse.expired_label": "समाप्त",
    "warehouse.days_remaining": "दिन शेष",
    "warehouse.live_stock_map": "लाइव स्टॉक मैप",
    "warehouse.in_stock": "स्टॉक में (HQ)",
    "warehouse.structural_aisle": "संरचनात्मक गलियारा",
    "warehouse.rack_section": "रैक अनुभाग",
    "warehouse.shelf_index": "शेल्फ इंडेक्स",
    "warehouse.expiry_date_label": "समाप्ति तिथि",
    "warehouse.shelf_life_remaining": "शेल्फ जीवन शेष",
    "warehouse.status": "स्थिति",
    "warehouse.po_number": "पीओ नंबर",
    "warehouse.supplier_name": "आपूर्तिकर्ता का नाम",
    "warehouse.items_ordered": "आदेशित वस्तुएं",
    "warehouse.total_value": "कुल मूल्य",
    "warehouse.creation_date": "निर्माण तिथि",
    "warehouse.actions": "कार्रवाई",

    // Stock Transfer
    "stock_transfer.title": "स्टॉक ट्रांसफर",
    "stock_transfer.subtitle": "वास्तविक समय सिंक के साथ शाखाओं के बीच स्टॉक ट्रांसफर करें",
    "stock_transfer.new_transfer": "नया ट्रांसफर",
    "stock_transfer.total_transfers": "कुल ट्रांसफर",
    "stock_transfer.this_session": "इस सत्र में",
    "stock_transfer.completed": "पूरा हुआ",
    "stock_transfer.success_transferred": "सफलतापूर्वक ट्रांसफर हुआ",
    "stock_transfer.branches_connected": "जुड़ी हुई शाखाएँ",
    "stock_transfer.active_locations": "सक्रिय स्थान",
    "stock_transfer.recent_transfers": "हाल के ट्रांसफर",
    "stock_transfer.no_transfers": "अभी तक कोई ट्रांसफर नहीं",
    "stock_transfer.transfers_in_history": "इतिहास में ट्रांसफर",
    "stock_transfer.create_transfer": "स्टॉक ट्रांसफर बनाएं",
    "stock_transfer.product_id": "उत्पाद आईडी",
    "stock_transfer.from_branch": "इस शाखा से",
    "stock_transfer.to_branch": "इस शाखा में",
    "stock_transfer.quantity": "मात्रा",
    "stock_transfer.notes": "टिप्पणियाँ (वैकल्पिक)",
    "stock_transfer.enter_qty": "मात्रा दर्ज करें",
    "stock_transfer.transfer_stock": "स्टॉक ट्रांसफर करें",
    "stock_transfer.how_it_works": "स्टॉक ट्रांसफर कैसे काम करता है",
    "stock_transfer.help_bullet_1": "उत्पाद आईडी दर्ज करें और स्रोत व गंतव्य शाखाओं का चयन करें",
    "stock_transfer.help_bullet_2": "सिस्टम स्वचालित रूप से स्रोत से कटौती करता है और गंतव्य शाखा में जोड़ता है",
    "stock_transfer.help_bullet_3": "ऑडिट ट्रेल और इन्वेंट्री ट्रैकिंग के लिए सभी ट्रांसफर लॉग किए जाते हैं",
    "stock_transfer.help_bullet_4": "स्टॉक अपडेट मिलीसेकंड के भीतर सभी शाखाओं में प्रसारित हो जाते हैं",
    "stock_transfer.help_bullet_5": "शाखाओं में संतुलन और नए स्टोर स्टॉक करने के लिए बिल्कुल सही",
    "stock_transfer.toast_fill_required": "कृपया सभी आवश्यक फ़ील्ड भरें",
    "stock_transfer.toast_different_branches": "स्रोत और गंतव्य शाखाएँ भिन्न होनी चाहिए",
    "stock_transfer.toast_insufficient_stock": "स्रोत शाखा में अपर्याप्त स्टॉक",
    "stock_transfer.toast_transfer_success": "स्टॉक सफलतापूर्वक ट्रांसफर हो गया!",
    "stock_transfer.toast_transfer_failed": "ट्रांसफर विफल: ",
    "stock_transfer.exceeds_stock": "उपलब्ध स्टॉक से अधिक है",
    "stock_transfer.available": "उपलब्ध:",

    // POS
    "pos.title": "बिक्री काउंटर (POS)",
    "pos.barcode": "बारकोड मोड",
    "pos.search_placeholder": "सामान, HSN कोड या बारकोड खोजें...",
    "pos.scan_placeholder": "कृपया बारकोड स्कैन करें...",
    "pos.table": "टेबल:",
    "pos.size": "साइज़:",
    "pos.color": "रंग:",
    "pos.cart_empty": "कार्ट खाली है",
    "pos.cart_sub": "उत्पादों पर क्लिक करें या बारकोड स्कैन करें",
    "pos.discount": "छूट लागू करें",
    "pos.payment_method": "भुगतान का तरीका",
    "pos.subtotal": "उप-कुल",
    "pos.tax": "जीएसटी (CGST + SGST)",
    "pos.grand_total": "कुल बिल राशि",
    "pos.park_bill": "बिल पार्क करें",
    "pos.pay_print": "भुगतान और प्रिंट (F4)",
    "pos.customer_acc": "ग्राहक खाता",
    "pos.add_new": "नया जोड़ें",
    "pos.billing_type": "बिलिंग प्रकार",
    "pos.send_kitchen": "रसोई में भेजें (KOT)",
    "pos.weight_label": "वजन दर्ज करें (Kg)",
    "pos.variants_label": "वेरिएंट चुनें",
    "pos.expiry_label": "समाप्ति तिथि",
    "pos.cash": "नकद",
    "pos.card": "कार्ड",
    "pos.upi": "UPI",
    "pos.split": "विभाजित भुगतान",
    "pos.credit": "उधार",
    "pos.qty": "मात्रा",
    "pos.price": "कीमत",
    "pos.new_sale": "नई बिक्री",
    "pos.return_sale": "वापसी / रिफंड",
    "pos.cashier": "कैशियर",
    "pos.total_transactions": "कुल लेनदेन",
    "pos.billing_history": "बिलिंग इतिहास",
    "pos.billing_history_subtitle": "सभी इनवॉइस देखें, दोबारा प्रिंट करें और प्रबंधित करें",
    "pos.invoices_log": "इनवॉइस लॉग",
    "pos.parked_bills": "पार्क किए गए बिल",
    "pos.today_bills": "आज के बिल",
    "pos.today_revenue": "आज का राजस्व",
    "pos.total_bills": "कुल बिल",
    "pos.search_invoice_placeholder": "इनवॉइस नंबर या ग्राहक का नाम खोजें...",
    "pos.no_invoices_found": "कोई इनवॉइस नहीं मिला",
    "pos.adjust_filters": "फ़िल्टर बदलकर देखें",
    "pos.walk_in_customer": "वॉक-इन ग्राहक",
    "pos.walk_in": "वॉक-इन",
    "pos.default": "डिफ़ॉल्ट",
    "pos.add_customer_btn": "जोड़ें",
    "pos.clear_selection": "चयन साफ़ करें",
    "pos.edit_customer": "ग्राहक संपादित करें",
    "pos.open_shift": "शिफ्ट शुरू करें",
    "pos.close_shift": "शिफ्ट बंद करें",
    "pos.starting_cash": "शुरुआती नकद",
    "pos.counter_number": "काउंटर संख्या",
    "pos.cashier_name": "कैशियर का नाम",


    // Metrics
    "metric.total_sales": "कुल बिक्री",
    "metric.gross_profit": "सकल लाभ",
    "metric.net_profit": "शुद्ध मुनाफा",
    "metric.gst_collected": "GST संग्रह",
    "metric.outstanding": "बकाया राशि",
    "metric.purchases": "कुल खरीद",
    "metric.expenses": "कुल खर्चे",
    "metric.customers": "कुल ग्राहक",
    "metric.products": "कुल उत्पाद",
    "metric.loan_debt": "लोन कर्ज़",
    "metric.sales_vs_expenses": " बिक्री बनाम खर्चे (दैनिक)",
    "metric.payment_status": " भुगतान स्थिति",
    "metric.monthly_pl": " मासिक लाभ-हानि (6 महीने)",
    "metric.expense_breakdown": " खर्चों का विवरण",
    "metric.profit_trend": "मुनाफ़े का ग्राफ़",
    "metric.recent_invoices": " हालिया बिल",
    "metric.stock_alerts": "️ स्टॉक अलर्ट",
    "metric.top_customers": "⭐ खास ग्राहक",

    // Voice
    "voice.welcome": "नमस्ते! आपके व्यापार डैशबोर्ड में स्वागत है।",
    "voice.cart_added": "सामान कार्ट में जोड़ दिया गया।",
    "voice.cart_removed": "सामान कार्ट से हटा दिया गया।",
    "voice.checkout_success": "बिल का भुगतान सफल और प्रिंट हो गया।",
    "voice.bill_parked": "बिल पार्क कर दिया गया।",
    "voice.scan_enabled": "बारकोड स्कैनर चालू।",
    "voice.scan_disabled": "बारकोड स्कैनर बंद।",
    "voice.kot_sent": "ऑर्डर रसोई में भेज दिया गया।",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("app_language") || "en";
  });
  const [voiceEnabled, setVoiceEnabled] = useState(() => {
    return localStorage.getItem("voice_enabled") !== "false";
  });

  useEffect(() => {
    localStorage.setItem("app_language", language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem("voice_enabled", String(voiceEnabled));
  }, [voiceEnabled]);

  // Prime speechSynthesis voices cache asynchronously on mount
  useEffect(() => {
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.getVoices();
      if (window.speechSynthesis.onvoiceschanged !== undefined) {
        window.speechSynthesis.onvoiceschanged = () => {
          window.speechSynthesis.getVoices();
        };
      }
    }
  }, []);

  const t = (key) => {
    // If translation doesn't exist, gracefully format the key into readable text
    // to prevent backend variable names (like settings.account_number) from showing up
    const fallbackText = key.includes('.') 
      ? key.split('.').pop().split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
      : key;
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS["en"]?.[key] || fallbackText;
  };

  const speak = (keyOrText, raw = false) => {
    if (!voiceEnabled || !window.speechSynthesis) return;
    try {
      window.speechSynthesis.cancel();
      const textToSpeak = raw ? keyOrText : t(keyOrText);
      const utterance = new SpeechSynthesisUtterance(textToSpeak);
      
      // Set rate & pitch to sound highly natural, clear, and perfectly human-like
      utterance.pitch = 1.0;
      utterance.rate = language === "hi" ? 0.88 : 0.92; // Slightly slower speed dramatically improves clarity and natural tone

      const voices = window.speechSynthesis.getVoices();
      let matchedVoice = null;

      if (language === "hi") {
        utterance.lang = "hi-IN";
        // Prioritize natural, organic Hindi voice actors over robotic system defaults
        matchedVoice = voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("google")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("natural")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("swara")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("hemant")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("rishi")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("madhur")) ||
                       voices.find(v => v.lang.startsWith("hi") && v.name.toLowerCase().includes("microsoft")) ||
                       voices.find(v => v.lang.startsWith("hi"));
      } else {
        utterance.lang = "en-US";
        // Prioritize natural, organic English voice actors
        matchedVoice = voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("natural")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("google") && v.name.toLowerCase().includes("us")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("google")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("premium")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("david")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("zira")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("samantha")) ||
                       voices.find(v => v.lang.startsWith("en") && v.name.toLowerCase().includes("rishi")) ||
                       voices.find(v => v.lang.startsWith("en"));
      }

      if (matchedVoice) {
        utterance.voice = matchedVoice;
        console.log(`[Voice Assistant] Selected human-quality voice: ${matchedVoice.name} (${matchedVoice.lang})`);
      }

      window.speechSynthesis.speak(utterance);
    } catch (e) {
      console.error("Speech Synthesis Error:", e);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, voiceEnabled, setVoiceEnabled, t, speak }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
